### ISSUE TITLE
Issue with partial match & some suggestions :)

### ISSUE THREAD

**Issue by HeraBlack0** [Kazi-Aidah/always-color-text#5]
Hi! It's me again! Sorry to add some more issues for you to work on ! 😅 

I don't know if it's intentional or not, but the plug in sometimes colors the words I don't want to when it contains another saved word in it. For exemple (I'm french, so those are french words):
- When I want to color the word "sol" (ground), it also colors the word "soleil" (sun), "soldat" (soldier) or "solide" (robust), where I don't want it to, because the word "sol" is in it.
- Same thing with "Mars" and "cauchemars" (Nightmares), or "Venus" and "devenus" (become).

I would like to clarify that it colors the entire word when the "partial match" is turned on, and only partially when it's turned off. (e.g. it will color the letters "sol" from "soleil" and will leave "eil" white).
Thank you for your patience with me! 😃 

---------

Also If you don't mind me putting that here, I would like to suggest some features for future updates that would greatly improve the use of the plug-in. It would be nice to be able to assign several words to one color (separating them with "-" or "," maybe?). Currently I need to assign separately a same words with different ending. "Dog "and "Dogs" needs two different colors even with the partial match turned on. It is even worse in french, since we have words like "Manger, mangé, mangés, mangée, mangées", so my "Always Color text" list is endless. Same thing with names, I would like to group up Mickael, Jackson and Mickael Jakson to one same color. 

Also, it would be a good addition to be able to sort all our colored words in the parameters (I have way too many! lol). Thanks again!

**Comment by Kazi-Aidah** [comment]
@HeraBlack0, Thank you for pointing this out! You've actually uncovered a big problem with the non-partial match feature that I hadn't fully realized. It's currently coloring characters inside larger words, which isn't the intended behavior for a "full word" match. I'll fix this so that, for example, "ate" is colored but not the "ate" in "date". (d"ate") I had partial-word coloring enabled by default, which is why I never caught this!

I'll fix this in the next update!!

As for your feature suggestions, thank you so much! Please keep them coming, they genuinely help make the plugin SO much better!

-   **Grouping Words:** I'll change the input box to allow commas, so you can assign multiple words to one color, like `[ Michael, Michael Jackson, Jackson ] [ color ]`.
-  **Sorting:** I can definitely add an A-Z sort option for your word list. Would that help you manage your long list?

Thanks again!

**Comment by Kazi-Aidah** [comment]
Hello @HeraBlack0, The issues you reported and the features you suggested have been implemented in **version 0.1.11**!!

- Fixed full-word/non-partial matching logic  
- Added comma-separated word grouping  
- Added sort options for managing word lists

Thank you for the detailed feedback and great suggestions! ❤️

**Comment by HeraBlack0** [comment]
Thank you for the imrovement! That was really quick! The added features help me so much not to be overwhelmed with all my patterns! 

I have some characters that still have the color issue when they're inside larger words though (The "sol" word), but some of them are fixed and it is much better. 

Thanks you again
